#include "healthai.h"

HealthAI::HealthAI() {}
QString HealthAI::answerQuestion(const QString &q)
{
    QString question = q.toLower();
    //all are generated by ai
    if (question.contains("fever"))
        return "A fever usually indicates your body is fighting an infection, dehydration,"
               " or a viral illness. Stay hydrated, rest well, and monitor your temperature"
               " regularly. If the fever persists for more than 2–3 days or goes above 102°F,"
               " consult a doctor.";
    if (question.contains("bp") || question.contains("blood pressure"))
        return "Normal blood pressure ranges around 120/80 mmHg. Consistently high BP may signal"
               " hypertension, while low BP can cause dizziness or fatigue. Monitoring trends is"
               " more important than single readings.";
    if (question.contains("medicine"))
        return "You can manage your medications in the Medicine tab. Ensure that dosage, frequency,"
               " and timings match your doctor’s prescription to avoid under or overdosing.";
    if (question.contains("lab") || question.contains("report"))
        return "You can upload and save your lab reports in the Lab Reports tab. Keeping a record"
               " helps track health changes over time and makes future consultations easier.";
    if (question.contains("sugar") || question.contains("glucose"))
        return "Normal fasting blood sugar is 70–99 mg/dL. Irregular or consistently high "
               "readings may indicate prediabetes or diabetes. Tracking your levels regularly"
               " helps early detection.";
    if (question.contains("weight"))
        return "Daily weight tracking helps identify sudden gains or losses which may signal "
               "underlying health issues. Compare weekly and monthly trends for better insights.";
    if (question.contains("diet") || question.contains("food"))
        return "A balanced diet with proteins, healthy fats, whole grains, and plenty of water"
               " supports overall health. Keeping a food log helps identify patterns affecting "
               "your energy or weight.";
    if (question.contains("sleep"))
        return "Adults typically need 7–9 hours of restful sleep. Poor sleep affects mood,"
               " immunity, hormones, and daily performance. Track your sleep pattern to identify"
               " irregularities.";
    if (question.contains("stress") || question.contains("anxiety"))
        return "Stress and anxiety can impact both mental and physical health. Try deep breathing,"
               " short breaks, physical activity, or journaling. Persistent symptoms may require"
               " professional guidance.";
    if (question.contains("exercise") || question.contains("workout"))
        return "Regular exercise boosts heart health, strengthens the body, and improves mood."
               " Tracking your daily activity helps you stay consistent and measure progress.";
    if (question.contains("water") || question.contains("hydration"))
        return "Proper hydration supports digestion, circulation, and energy levels. Aim for 6–8 "
               "glasses of water a day, but adjust according to weather and activity level.";
    if (question.contains("heart") || question.contains("chest"))
        return "Chest pain or tightness can be caused by stress, acidity, or heart-related issues."
               " Persistent, severe, or radiating pain requires immediate medical attention.";
    if (question.contains("temperature"))
        return "Normal body temperature is around 98.6°F (37°C). A consistently elevated"
               " temperature may indicate infection or inflammation. Monitor closely if levels"
               " stay high.";
    if (question.contains("pain"))
        return "Pain can vary widely depending on cause — from muscular strain to infection."
               " Track the intensity, duration, and location to help identify patterns or triggers.";
    if (question.contains("covid") || question.contains("corona"))
        return "COVID-19 symptoms commonly include fever, cough, fatigue, and loss of taste or"
               " smell. Monitor symptoms, isolate if needed, and follow current health guidelines.";
    if (question.contains("headache"))
        return "Headaches may result from stress, dehydration, eye strain, or poor sleep. Rest,"
               " hydration, and reduced screen time can help relieve symptoms.";
    if (question.contains("vomit") || question.contains("nausea"))
        return "Nausea or vomiting can be caused by infection, acidity, food poisoning, or"
               " dehydration. Sip water slowly and rest. Seek help if vomiting is persistent.";
    if (question.contains("throat"))
        return "A sore throat often comes from infection, dryness, or irritation. Warm fluids,"
               " saltwater gargles, and rest can help reduce discomfort.";
    if (question.contains("cold") || question.contains("flu"))
        return "Cold and flu symptoms may include cough, fever, runny nose, and fatigue. Rest,"
               " warm fluids, and hydration support quick recovery.";
    if (question.contains("period") || question.contains("menstrual"))
        return "Tracking your menstrual cycle helps understand regularity, symptoms, and hormonal"
               " changes. Severe pain, excessive bleeding, or irregular cycles should be evaluated"
               " by a doctor.";
    if (question.contains("paracetamol") || question.contains("acetaminophen"))
        return "Paracetamol is commonly used to reduce fever and relieve mild to moderate pain."
               " Avoid exceeding the maximum daily dose, as it may cause liver damage.";

    if (question.contains("ibuprofen"))
        return "Ibuprofen helps reduce pain, fever, and inflammation by blocking certain "
               "chemicals in the body. Take it after food to avoid stomach irritation and"
               " do not exceed the prescribed dose.";
    if (question.contains("panadol"))
        return "Panadol contains paracetamol and is used for fever and mild pain relief. "
               "Avoid taking it with other paracetamol-based medicines to prevent overdose.";
    if (question.contains("brufen"))
        return "Brufen is an anti-inflammatory and pain-relieving medicine. Take it with "
               "food or milk to prevent acidity, and follow the recommended dose carefully.";
    if (question.contains("flagyl") || question.contains("metronidazole"))
        return "Flagyl (Metronidazole) treats bacterial and protozoal stomach infections."
               " Avoid alcohol during treatment and complete the full course as prescribed.";
    if (question.contains("augmentin") || question.contains("amoxicillin"))
        return "Augmentin is a broad-spectrum antibiotic for bacterial infections. Always"
               " complete the full course even if symptoms improve to prevent resistance.";
    if (question.contains("azithromycin"))
        return "Azithromycin is an antibiotic used for respiratory or throat infections. "
               "Take it as prescribed, usually once daily, and complete the full course.";
    if (question.contains("antibiotic"))
        return "Antibiotics are effective only against bacterial infections, not viral "
               "illnesses. Always finish the prescribed course and follow dosing instructions.";
    if (question.contains("cetirizine") || question.contains("allergy"))
        return "Cetirizine is an antihistamine used for allergies and flu-related symptoms."
               " It may cause mild drowsiness; avoid driving if affected.";
    if (question.contains("calpol"))
        return "Calpol is a paracetamol-based syrup for fever and pain relief in children. "
               "Use the correct dose according to age and weight to avoid overdose.";
    if (question.contains("ORS") || question.contains("rehydration"))
        return "ORS (Oral Rehydration Solution) helps restore fluids and electrolytes lost "
               "due to dehydration. Sip frequently in small amounts for best effect.";
    if (question.contains("gaviscon") || question.contains("acidity"))
        return "Gaviscon relieves heartburn and acidity by forming a protective layer in the"
               " stomach. Avoid spicy, oily, and heavy foods during treatment.";
    if (question.contains("omeprazole") || question.contains("gastric"))
        return "Omeprazole reduces stomach acid and protects the stomach lining. Take it before"
               " breakfast for maximum effectiveness and avoid skipping doses.";
    if (question.contains("multivitamin") || question.contains("vitamin"))
        return "Multivitamins support overall health, immunity, and energy. Consistency is more"
               " important than high doses; follow the recommended daily allowance.";
    if (question.contains("painkiller") || question.contains("pain killer"))
        return "Painkillers help relieve pain but should not be overused. Track pain patterns,"
               " follow dosing instructions, and consult a doctor for persistent pain.";
    if (question.contains("antacid"))
        return "Antacids neutralize excess stomach acid and relieve heartburn or indigestion."
               " Avoid heavy meals, late-night eating, and follow the recommended dose.";
    if (question.contains("cough syrup") || question.contains("cough"))
        return "Cough syrups target either dry or chesty coughs. Choose one that matches your "
               "symptoms, follow dosing instructions, and stay hydrated.";
    if (question.contains("vomit") || question.contains("nausea"))
        return "Anti-nausea medicines can reduce vomiting and discomfort. Stay hydrated, eat "
               "small bland meals, and consult a doctor if symptoms persist.";
    if (question.contains("diarrhea") || question.contains("loose motion"))
        return "For diarrhea, staying hydrated is crucial. Medicines can help, but avoid oily,"
               " spicy, or heavy foods and consult a doctor for prolonged cases.";
    if (question.contains("inhaler") || question.contains("asthma"))
        return "Inhalers help open airways during asthma attacks. Use proper inhalation technique,"
               " follow the prescribed dose, and seek urgent care if symptoms worsen.";

    return "I didn’t understand that completely, but I can help with medicines, lab reports, and general health guidance!";
}
